# Generated by Django 4.1.4 on 2022-12-18 12:34

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.get_upload_path),
        ),
    ]
